name: "GitHub Action for Firebase"
author: "Jeremy Shore"
description: "Wraps the firebase-tools CLI to enable common commands."

branding:
  icon: "package"
  color: "gray-dark"

outputs:
  response:
    description: "Response from the firebase command executed"

runs:
  using: "docker"
  image: "docker://suicxde007/firebase-action:v14.10.1"
